name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  merge_group:

permissions:
  id-token: write # This is required for requesting the JWT
  security-events: write
  contents: read
  actions: read # This is required for actions/checkout
  issues: write
  pull-requests: write
  checks: write # needed for spotbugs

jobs:

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Setup settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          override: true
          servers: |
              [{
                  "id": "repo.jenkins-ci.org",
                  "username": "${{ secrets.OSS_JENKINS_USER }}",
                  "password": "${{ secrets.OSS_JENKINS_PASS }}"
              }]

      - name: publish release package
        if: contains( github.ref, 'main' ) || contains( github.base_ref, 'main' )
        env:
          JENKINS_MAVEN_PASS: ${{ secrets.JENKINS_MAVEN_PASS }}
        run: ./mvnw deploy -DskipTests -DskipITs
