name: CI

on:
    push:
        tags:
            - 'v*'

permissions:
    id-token: write # This is required for requesting the JWT
    security-events: write
    contents: read
    actions: read # This is required for actions/checkout
    issues: write
    pull-requests: write
    checks: write # needed for spotbugs

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Check out
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    distribution: 'adopt'
                    java-version: 11
                    cache: 'maven'

            -   name: Setup settings.xml
                uses: s4u/maven-settings-action@v3.1.0
                with:
                    override: true
                    servers: |
                        [{
                            "id": "repo.jenkins-ci.org",
                            "username": "${{ secrets.OSS_JENKINS_USER }}",
                            "password": "${{ secrets.OSS_JENKINS_PASS }}"
                        }]

            -   name: publish release package
                run: ./mvnw deploy -DskipTests -DskipITs

            -   name: tag-and-release
                id: tag-and-release
                uses: avakar/tag-and-release@v1
                with:
                    release_name: ${{ github.event.inputs.releaseversion }}
                    tag_name: v${{ github.event.inputs.releaseversion }}
                    draft: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
